# Generated by Django 5.0 on 2024-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skin_type',
            field=models.CharField(default='Default Skin Type', max_length=500),
        ),
    ]
