# Generated by Django 5.0 on 2024-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=500)),
                ('sub_title', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
