# Generated by Django 5.0 on 2024-01-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_products_skin_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default='None Specified', max_length=500),
        ),
    ]
